src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Email__c</fullName>
        <externalId>true</externalId>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Job_Application__c.object
<CustomObject>
    <description>Represents a candidate&apos;s application to a position</description>
    <fields>
        <fullName>Candidate__c</fullName>
        <description>Related To: Candidate
Related List Label: Job Applications</description>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Related To: Position
Related List Label: Job Applications</description>
        <label>Position</label>
        <referenceTo>Position__c</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Review Resume</fullName>
                </value>
                <value>
                    <fullName>Phone Screen</fullName>
                </value>
                <value>
                    <fullName>Schedule Interviews</fullName>
                </value>
                <value>
                    <fullName>Extend an Offer</fullName>
                </value>
                <value>
                    <fullName>Hired</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Open - Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - Filled</fullName>
                </value>
                <value>
                    <fullName>Closed - Not Approved</fullName>
                </value>
                <value>
                    <fullName>Closed - Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MR_EmailSenderTriggerTest.cls
/**
 * Created by admin_1 on 26/09/2017.
 */
@isTest
private class MR_EmailSenderTriggerTest {
	@testSetup static void dataFactory() {
		// data factory
		// need to add extra contact because emailSenderTrigger is base on roll back email sending to a random contact
		Contact contact = new Contact(
				Salutation = 'Ms.',
				LastName = 'Nghia',
				Email='test@mulodo.com'
		);
		insert contact;

		Candidate__c testCan = new Candidate__c(
				First_Name__c = 'Nghia',
				Last_Name__c ='Nguyen',
				Phone__c = '01212132815',
				Email__c = 'nguyen.nghia@mulodo.com'
		);
		insert testCan;
		Position__c testPos = new Position__c(Name='C# Test Pos');
		insert testPos;
		Job_Application__c testApp = new Job_Application__c(Candidate__c = testCan.Id, Position__c = testPos.Id, Status__c ='New');
		insert testApp;
	}

	@isTest static void TestOnCreate() {
		// get data from test factory
		Candidate__c testCan = [SELECT Id FROM Candidate__c WHERE First_Name__c = 'Nghia'];
		Position__c testPos = [SELECT Id FROM Position__c WHERE Name = 'C# Test Pos'];

		// start test
		Test.startTest();
			Job_Application__c newApp = new Job_Application__c(
					Candidate__c = testCan.Id,
					Position__c = testPos.Id,
					Status__c ='Schedule Interviews'
			);
			insert newApp;
			Integer emailInvocations = Limits.getEmailInvocations();
		Test.stopTest();
		System.assert(newApp.Id != null, 'New Application created');
		System.assertEquals(2, emailInvocations, 'An email should be send');
		/**@TODO Add System Assert Here*/
	}

	@isTest static void TestOnUpdate() {
		// get data from test factory
		Job_Application__c existsApp = [SELECT Id, Status__c FROM Job_Application__c WHERE Status__c = 'New' LIMIT 1];

		// test
		Test.startTest();
			existsApp.Status__c = 'Schedule Interviews';
			update existsApp;
			Integer emailInvocations = Limits.getEmailInvocations();
		Test.stopTest();
		System.assertEquals(existsApp.Status__c, 'Schedule Interviews', 'Update Exist App Success');
		System.assertEquals(2, emailInvocations, 'An email should be send');
	}

}