src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HS Diploma,</fullName>
                </value>
                <value>
                    <fullName>BA/BS,</fullName>
                </value>
                <value>
                    <fullName>MA,MS,MBA,</fullName>
                </value>
                <value>
                    <fullName>Ph.D</fullName>
                </value>
                <value>
                    <fullName>Post Doc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <externalId>true</externalId>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <externalId>true</externalId>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/candidateTestAngular.cls
/**
 * Created by remjx on 29-Sep-17.
 */
/**	Description: A controller to send data in JSON type to Angular controller
	@ControllerExtension
*/
public with sharing class candidateTestAngular {
	// procedure constructor
	public candidateTestAngular(ApexPages.StandardController controller) {

	}
	@RemoteAction
	public static string getJSONCandidates() {
		// serialize to JSON
		return JSON.serialize([SELECT First_Name__c, Last_Name__c FROM Candidate__c]);
	}

	/** Description: To Test Pick List Value From Apex and describe on form
		@Remoting Javascript
	*/
	@RemoteAction
	public static string getEducationPickList() {
		Schema.DescribeFieldResult educationField = Candidate__c.Education__c.getDescribe();
		List<Schema.PicklistEntry> countryPickList = educationField.getPicklistValues();
		return JSON.serialize(countryPickList);
	}

	@AuraEnabled
	public List<Candidate__c> getListCandidate() {
		return [SELECT First_Name__c, Last_Name__c FROM Candidate__c];
	}
}