src/objects/Candidate__c.object
<CustomObject>
    <description>Represents an applicant who might apply for one or more positions</description>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Country_List</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Education__c</fullName>
        <label>Education</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HS Diploma,</fullName>
                </value>
                <value>
                    <fullName>BA/BS,</fullName>
                </value>
                <value>
                    <fullName>MA,MS,MBA,</fullName>
                </value>
                <value>
                    <fullName>Ph.D</fullName>
                </value>
                <value>
                    <fullName>Post Doc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MR_CandidateFormCE.cls
/**
 * Created by admin_1 on 28/09/2017.
 */
public class MR_CandidateFormCE {

	public MR_CandidateFormCE(ApexPages.StandardController controller) {
	}
// TO TEST ANGULAR
//	@RemoteAction
//	public static Id createAccount(String name,String fax){
//
//		Account acc = new Account();
//		acc.Name = name;
//		acc.Fax = fax;
//
//		insert acc;
//
//		return acc.Id;
//	}
	/** Description: Return Country Pick List for candidateCustomFormPage
	*/
	public static List<Schema.PicklistEntry> getCountryPickList() {
		Schema.DescribeFieldResult countryField = Candidate__c.Country__c.getDescribe();
		List<Schema.PicklistEntry> countryPickList = countryField.getPicklistValues();
		return countryPickList;
	}

	/** Description: Return Education Pick List for candidateCustomFormPage
	*/
	public static List<Schema.PicklistEntry> getEducationPickList() {
		Schema.DescribeFieldResult educationField = Candidate__c.Education__c.getDescribe();
		List<Schema.PicklistEntry> educationPickList = educationField.getPicklistValues();
		return educationPickList;
	}
}